### ISSUE TITLE
Add support to named package generation in import

### ISSUE THREAD

**Issue by sorrentinov** [bsorrentino/zx-powerapps-cli#6]
Hi,

Should be useful to have a new parameter in zx-import-solution to generate the zip with a custom name

For example:
```
npx zx-import-solution  [--authindex <n>] 
                        [--solution <solution folder>] 
                        [--package Managed|Unmanaged|Both] 
                        [--packonly]
                        [--packname <package name>] 
```

By specifying the "packname" (only if there is a packonly) the zip file should be generated with that name.
This could be useful in pipeline to choose a proper namer

Regards
Vincenzo

**Comment by bsorrentino** [comment]
Hi @sorrentinov thanks for feedback 

I followed the standard behaviour from MSFT nevertheless such feature could be useful 

I'll work on it as soon as possible

**Comment by bsorrentino** [comment]
Hi @sorrentinov 

I reviewed code and the name of zip is the same of solution folder so I suppose will be easier work on folder name rather than add a new parameter

**Comment by sorrentinov** [comment]
Hi @bsorrentino 

The folder name refers to the Power App solution "unique name", so we do not change it. However, if you do not think it useful to add the parameter I find an alternative solution. 

Thanks
Vincenzo

**Comment by bsorrentino** [comment]
> Hi @bsorrentino
> 
> The folder name refers to the Power App solution "unique name", so we do not change it. However, if you do not think it useful to add the parameter I find an alternative solution.
> 
> Thanks Vincenzo

Hi @sorrentinov  was just to understand reasons behind the request

Import was designed to distribute the solution in the cloud and the zip archive is just a temporary generated envelope. Your request implies that you have particular need  probably want share or store archive  somewhere.

However in a pipeline to rename the zip archive is pretty straightforward

**Comment by sorrentinov** [comment]
Simply in a pipeline I need to generate a name also including the package version. For sure I can generate  it and move the file with the desired name. Was only to avoid a step

But I'm agree with you can be unnecessary add the parameter and execute a step more

**Comment by bsorrentino** [comment]
> Simply in a pipeline I need to generate a name also including the package version. For sure I can generate it and move the file with the desired name. Was only to avoid a step
> 
> But I'm agree with you can be unnecessary add the parameter and execute a step more

Hi @sorrentinov  I consider your statement `I need to generate a name also including the package version` very interesting. So I've released version `2.0.8` that include the solution's version as part of zip name. 

Hope this help

**Comment by sorrentinov** [comment]
Thanks @bsorrentino, I see the release `2.0.8` but I'm unable to see the parameter's name to use in the documentation. Is it always generated including the version in the zip file?

**Comment by bsorrentino** [comment]
There isn't new parameter but the generated zip name now contains the solution version

**Comment by sorrentinov** [comment]
Ok, I thought of a parameter that could say "include or not include the version", but could be redundant

**Comment by sorrentinov** [comment]
What about a parameter "--includeversion"?

**Comment by bsorrentino** [comment]
Why do you need parameter ? the version is now part immutable of the archive and (eventually) also in pipeline will be simple refers to it

**Comment by sorrentinov** [comment]
By default I thing is good practice to generate a package that includes the version. So I really appreciated the new version.
Sometime could be useful to generate a package with same name (not including the version). For example we need in a pipeline to publish a package in SharePoint with same name to permit file versioning.

**Comment by bsorrentino** [comment]
Hi @sorrentinov  

I've release version `2.0.9` with `--noversion` parameter as requested. 

Note:
> I've added `--noversion` because consider that default behaviour must include version in generated zip
