### ISSUE TITLE
Unable to export solution when there are two authentication profiles with *

### ISSUE THREAD

**Issue by sorrentinov** [bsorrentino/zx-powerapps-cli#9]
Hi

I noticed that when I set up 2 authentication profiles and try to export a solution, the CLI detects a wrong profile:
For example, in the following figure I'm trying to export a solution from a profile with index 6, but the CLI connected to the profile 7:
 
![ZxExport_issue](https://github.com/bsorrentino/zx-powerapps-cli/assets/4456300/4b006851-8213-42f6-a3f8-94a15adb2a7e)

**Comment by bsorrentino** [comment]
hi @sorrentinov 

in the attached screenshot I see two selected profiles ... this looks weird . can you confirm that you, currently, have two active profiles ?

**Comment by sorrentinov** [comment]
hi @bsorrentino 

This happen when you have mixed profiles DATAVERSE/UNIVERSAL, so you can have one active profile for type.....one for DATAVERSE and one for UNIVERSAL.
Actually DATAVERSE type is deprecated, so I can solve removing all DATAVERSE profiles and recreate it as UNIVERSAL. But just let you know that when you have mixed types you can have two profiles labelled with "*"

**Comment by bsorrentino** [comment]
hi @sorrentinov 

release `2.3.0` has been released with fix
